/*
 * BirdDog RESTful API 2.0
 *
 * Unofficial idiomatic rust bindings for the BirdDog RESTful API 2.0 generated using OpenAPI Generator.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalogaudiosetupGet200Response {
    #[serde(rename = "AnalogAudioInGain", skip_serializing_if = "Option::is_none")]
    pub analog_audio_in_gain: Option<String>,
    #[serde(rename = "AnalogAudioOutGain", skip_serializing_if = "Option::is_none")]
    pub analog_audio_out_gain: Option<String>,
    #[serde(rename = "AnalogAudiooutputselect", skip_serializing_if = "Option::is_none")]
    pub analog_audiooutputselect: Option<String>,
}

impl AnalogaudiosetupGet200Response {
    pub fn new() -> AnalogaudiosetupGet200Response {
        AnalogaudiosetupGet200Response {
            analog_audio_in_gain: None,
            analog_audio_out_gain: None,
            analog_audiooutputselect: None,
        }
    }
}

