/*
 * BirdDog RESTful API 2.0
 *
 * Unofficial idiomatic rust bindings for the BirdDog RESTful API 2.0 generated using OpenAPI Generator.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Birddogsil2encGet200ResponseSrt {
    #[serde(rename = "ConnectionURL", skip_serializing_if = "Option::is_none")]
    pub connection_url: Option<String>,
    #[serde(rename = "Encryption", skip_serializing_if = "Option::is_none")]
    pub encryption: Option<String>,
    #[serde(rename = "IPAddress", skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    #[serde(rename = "Port", skip_serializing_if = "Option::is_none")]
    pub port: Option<String>,
    #[serde(rename = "latency", skip_serializing_if = "Option::is_none")]
    pub latency: Option<String>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    #[serde(rename = "passphrase", skip_serializing_if = "Option::is_none")]
    pub passphrase: Option<String>,
    #[serde(rename = "pbkeylen", skip_serializing_if = "Option::is_none")]
    pub pbkeylen: Option<String>,
    #[serde(rename = "streamid", skip_serializing_if = "Option::is_none")]
    pub streamid: Option<String>,
}

impl Birddogsil2encGet200ResponseSrt {
    pub fn new() -> Birddogsil2encGet200ResponseSrt {
        Birddogsil2encGet200ResponseSrt {
            connection_url: None,
            encryption: None,
            ip_address: None,
            port: None,
            latency: None,
            mode: None,
            passphrase: None,
            pbkeylen: None,
            streamid: None,
        }
    }
}
