/*
 * BirdDog RESTful API 2.0
 *
 * Unofficial idiomatic rust bindings for the BirdDog RESTful API 2.0 generated using OpenAPI Generator.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Birddogsil2encGet200ResponseRtsp {
    #[serde(rename = "AuthEnable", skip_serializing_if = "Option::is_none")]
    pub auth_enable: Option<String>,
    #[serde(rename = "ConnectionURL", skip_serializing_if = "Option::is_none")]
    pub connection_url: Option<String>,
    #[serde(rename = "Password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "Port", skip_serializing_if = "Option::is_none")]
    pub port: Option<String>,
    #[serde(rename = "StreamName", skip_serializing_if = "Option::is_none")]
    pub stream_name: Option<String>,
    #[serde(rename = "UserName", skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
}

impl Birddogsil2encGet200ResponseRtsp {
    pub fn new() -> Birddogsil2encGet200ResponseRtsp {
        Birddogsil2encGet200ResponseRtsp {
            auth_enable: None,
            connection_url: None,
            password: None,
            port: None,
            stream_name: None,
            user_name: None,
        }
    }
}

