/*
 * BirdDog RESTful API 2.0
 *
 * Unofficial idiomatic rust bindings for the BirdDog RESTful API 2.0 generated using OpenAPI Generator.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Birddogsil2codecGet200Response {
    #[serde(rename = "DISABLE", skip_serializing_if = "Option::is_none")]
    pub disable: Option<models::Birddogsil2codecGet200ResponseDisable>,
    #[serde(rename = "HX", skip_serializing_if = "Option::is_none")]
    pub hx: Option<models::Birddogsil2codecGet200ResponseHx>,
    #[serde(rename = "RTMP", skip_serializing_if = "Option::is_none")]
    pub rtmp: Option<models::Birddogsil2codecGet200ResponseRtmp>,
    #[serde(rename = "RTSP", skip_serializing_if = "Option::is_none")]
    pub rtsp: Option<models::Birddogsil2codecGet200ResponseRtmp>,
    #[serde(rename = "SRT", skip_serializing_if = "Option::is_none")]
    pub srt: Option<models::Birddogsil2codecGet200ResponseRtmp>,
}

impl Birddogsil2codecGet200Response {
    pub fn new() -> Birddogsil2codecGet200Response {
        Birddogsil2codecGet200Response {
            disable: None,
            hx: None,
            rtmp: None,
            rtsp: None,
            srt: None,
        }
    }
}
