/*
 * BirdDog RESTful API 2.0
 *
 * Unofficial idiomatic rust bindings for the BirdDog RESTful API 2.0 generated using OpenAPI Generator.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Birddogsil2codecGet200ResponseRtmp {
    #[serde(rename = "BitrateControl", skip_serializing_if = "Option::is_none")]
    pub bitrate_control: Option<String>,
    #[serde(rename = "Custom", skip_serializing_if = "Option::is_none")]
    pub custom: Option<models::Birddogsil2codecGet200ResponseRtmpCustom>,
    #[serde(rename = "ModeSel", skip_serializing_if = "Option::is_none")]
    pub mode_sel: Option<String>,
    #[serde(rename = "high", skip_serializing_if = "Option::is_none")]
    pub high: Option<models::Birddogsil2codecGet200ResponseDisableHigh>,
    #[serde(rename = "low", skip_serializing_if = "Option::is_none")]
    pub low: Option<models::Birddogsil2codecGet200ResponseDisableCustom>,
    #[serde(rename = "med", skip_serializing_if = "Option::is_none")]
    pub med: Option<models::Birddogsil2codecGet200ResponseDisableMed>,
    #[serde(rename = "ultra", skip_serializing_if = "Option::is_none")]
    pub ultra: Option<models::Birddogsil2codecGet200ResponseDisableUltra>,
}

impl Birddogsil2codecGet200ResponseRtmp {
    pub fn new() -> Birddogsil2codecGet200ResponseRtmp {
        Birddogsil2codecGet200ResponseRtmp {
            bitrate_control: None,
            custom: None,
            mode_sel: None,
            high: None,
            low: None,
            med: None,
            ultra: None,
        }
    }
}

