/*
 * BirdDog RESTful API
 *
 * Unofficial idiomatic rust bindings for the BirdDog RESTful API 2.0 generated using OpenAPI Generator.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BirddogptzsetupPostRequest {
    /// Range from 0 to 21
    #[serde(rename = "PanSpeed", skip_serializing_if = "Option::is_none")]
    pub pan_speed: Option<String>,
    /// Range from 0 to 18
    #[serde(rename = "TiltSpeed", skip_serializing_if = "Option::is_none")]
    pub tilt_speed: Option<String>,
    /// Range from 0 to 7
    #[serde(rename = "ZoomSpeed", skip_serializing_if = "Option::is_none")]
    pub zoom_speed: Option<String>,
}

impl BirddogptzsetupPostRequest {
    pub fn new() -> BirddogptzsetupPostRequest {
        BirddogptzsetupPostRequest {
            pan_speed: None,
            tilt_speed: None,
            zoom_speed: None,
        }
    }
}
