/*
 * BirdDog RESTful API 2.0
 *
 * Unofficial idiomatic rust bindings for the BirdDog RESTful API 2.0 generated using OpenAPI Generator.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BirddogadvancesetupResponse {
    #[serde(rename = "Brightness", skip_serializing_if = "Option::is_none")]
    pub brightness: Option<String>,
    #[serde(rename = "BrightnessComp", skip_serializing_if = "Option::is_none")]
    pub brightness_comp: Option<String>,
    #[serde(rename = "CompLevel", skip_serializing_if = "Option::is_none")]
    pub comp_level: Option<String>,
    #[serde(rename = "GammaOffset", skip_serializing_if = "Option::is_none")]
    pub gamma_offset: Option<String>,
    #[serde(rename = "HighResolution", skip_serializing_if = "Option::is_none")]
    pub high_resolution: Option<String>,
    #[serde(rename = "VideoEnhancement", skip_serializing_if = "Option::is_none")]
    pub video_enhancement: Option<String>,
}

impl BirddogadvancesetupResponse {
    pub fn new() -> BirddogadvancesetupResponse {
        BirddogadvancesetupResponse {
            brightness: None,
            brightness_comp: None,
            comp_level: None,
            gamma_offset: None,
            high_resolution: None,
            video_enhancement: None,
        }
    }
}

