/*
 * BirdDog RESTful API
 *
 * Unofficial idiomatic rust bindings for the BirdDog RESTful API 2.0 generated using OpenAPI Generator.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BirddogdetsetupPostRequest {
    /// DEFAULT, LOW, MIDDLE, HIGH, WIDE
    #[serde(rename = "Bandwidth", skip_serializing_if = "Option::is_none")]
    pub bandwidth: Option<String>,
    /// TYPE1, TYPE2, TYPE3, TYPE4, TYPE5
    #[serde(rename = "BwBalance", skip_serializing_if = "Option::is_none")]
    pub bw_balance: Option<String>,
    /// Range (0 to 7)
    #[serde(rename = "Crispening", skip_serializing_if = "Option::is_none")]
    pub crispening: Option<String>,
    /// On, Off
    #[serde(rename = "Detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    /// Range (0 to 4)
    #[serde(rename = "HighLightDetail", skip_serializing_if = "Option::is_none")]
    pub high_light_detail: Option<String>,
    /// Range (-2 to 2)
    #[serde(rename = "HvBalance", skip_serializing_if = "Option::is_none")]
    pub hv_balance: Option<String>,
    /// Range (0 to 7)
    #[serde(rename = "Limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<String>,
    /// Range (0 to 7)
    #[serde(rename = "SuperLow", skip_serializing_if = "Option::is_none")]
    pub super_low: Option<String>,
}

impl BirddogdetsetupPostRequest {
    pub fn new() -> BirddogdetsetupPostRequest {
        BirddogdetsetupPostRequest {
            bandwidth: None,
            bw_balance: None,
            crispening: None,
            detail: None,
            high_light_detail: None,
            hv_balance: None,
            limit: None,
            super_low: None,
        }
    }
}
