/*
 * BirdDog RESTful API
 *
 * Unofficial idiomatic rust bindings for the BirdDog RESTful API 2.0 generated using OpenAPI Generator.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecodeTransportPostRequest {
    /// Multicast, TCP, Multi-TCP, UDP
    #[serde(rename = "rxpm", skip_serializing_if = "Option::is_none")]
    pub rxpm: Option<String>,
}

impl DecodeTransportPostRequest {
    pub fn new() -> DecodeTransportPostRequest {
        DecodeTransportPostRequest {
            rxpm: None,
        }
    }
}

